### ISSUE TITLE
프로토타이핑

### ISSUE THREAD

**Issue by hajiyoooon** [hajiyoooon/oive#10]
**what is prototype?**
(읽으면 좋아요~)
- https://brunch.co.kr/@ebprux/418
- https://blogs.adobe.com/creativedialogue/design-ko/everything-you-need-to-know-about-wireframes-and-prototypes/

**해야 할 일**
- 2.17(화) 까지 프로토타입을 그리기
- 툴은 아무거나 사용 가능

**추천 툴**
- 종이랑 펜
- 카카오 오븐(https://ovenapp.io/) : 온라인으로 이용 가능
- 구글에 "프로토타이핑 툴" 이라고 검색하기

**Comment by hajiyoooon** [comment]
https://ovenapp.io/view/pdU6GSTZJlLhohK4fYIjfDEOPnkRQyix/yCyll

**Comment by hajiyoooon** [comment]
https://ovenapp.io/view/IUlfjGQ5ynBqWPvuNSNQpg1yYQBSGsWo/74KFA

**Comment by ee249** [comment]
**https://ovenapp.io/view/gXw0H6nctI2yx121PZJ2QmXeFxO4ztnI/uO7IW**

**Comment by hajiyoooon** [comment]
de8407b5-102d-aac8-2e6a-fe7f44daa2e0
