### ISSUE TITLE
디비 구현

### ISSUE THREAD

**Issue by hajiyoooon** [hajiyoooon/oive#14]
DB 공유 코드
- de8407b5-102d-aac8-2e6a-fe7f44daa2e0

해야 할 일
- DB 테이블 만들기
- 정규화

**Comment by soykim-snail** [comment]
10f98951-e7fd-b873-2288-ee00f88253cc

'대학교'와 '자격증' 테이블입니다.

**Comment by ee249** [comment]
4a22be79-f9db-c206-3f5f-d52920908600
