### ISSUE TITLE
뷰 구현

### ISSUE THREAD

**Issue by hajiyoooon** [hajiyoooon/oive#17]
https://docs.google.com/spreadsheets/d/11v4IQLcSmhtTv6UA88tTVv4bNQnBjRrh0pR95K0X794/edit?usp=sharing

**Comment by soykim-snail** [comment]
https://github.com/soykim-snail/projectpreparing/blob/master/meeting%20log
온라인 회의 회의록입니다. 1차와 2차

**Comment by hajiyoooon** [comment]
2020-03-02 뷰 관련 사항 정리입니다
master에 현재 이 버전이 적용되어 있고, 두 분의 브랜치에도 동일하게 적용시켜드렸습니다.
-----

1. 앞으로는 base.jsp를 복사해서 작업을 하면 됩니다. 지금까지 작업사항도 복붙해주시면 감사하겠습니당
- base.jsp를 작업하면서 nav, footer등등 몇개 클래스를 좀 손봤어요ㅎㅎ; 혹시 이상있으면 말해주세요

2. 충돌에 대해서
- 일단 충돌이 나면 
- 가장 최근의 작업물을 덮어씌워서 해결하는 방법
- 파일명을 다르게 만들어서 해결하는 방법 ex) example.jsp -> example2.jsp
- 제가 한 것처럼 버전 비교해서 적용하기가 있는데요
맨 마지막을 어떻게 하면 이해하기 쉽게 설명할까 고민을 하고 있는데 잘 모르겠네요... 일단 이클립스로 하는건 보류할게요

3. HomeController에 각 페이지로 접속할 수 있는 url을 매핑했어요
- / : 메인 로그인 페이지
- /join : 회원가입
- /self_introduce/list : 자소서 목록
- /profile : 프로필
- /form : university_form 파일
- /self_introduce/write/{self_introduce_id} : 자소서 작성 페이지

이렇게 매핑했으니까 앞으로 작업하실때 홈컨트롤러 수정 안하셔도 될 것 같아요!
