### ISSUE TITLE
team logo

### ISSUE THREAD

**Issue by soykim-snail** [hajiyoooon/oive#18]
team logo SVG 파일을 제작한다.

**Comment by soykim-snail** [comment]
SVG 로고 그리기 힘들지 않나요?
inkscape라는 오픈소스 SVG 편집툴을 사용해서 로고 두 개를 그려봤어요.
둘중에서 사용 하면 어떨까 제안드립니다.
[https://github.com/soykim-snail/projectpreparing/blob/master/oive.svg](url)
[https://github.com/soykim-snail/projectpreparing/blob/master/oive.svg2](url)

편집툴은 https://inkscape.org/  에서 다운로드 받을 수 있습니다.

**Comment by hajiyoooon** [comment]
우왕 신기하네요ㅠㅠ 그런데 링크가 안열려요..!ㅠㅠㅠㅠ

**Comment by soykim-snail** [comment]
[oive.svg](url)
[oive2.svg](url)
프로젝트 repository에 올렸습니다.

**Comment by soykim-snail** [comment]
https://github.com/hajiyoooon/oive/blob/master/oive.svg
https://github.com/hajiyoooon/oive/blob/master/oive2.svg

**Comment by soykim-snail** [comment]
,,
